version: '2'
services:
    elasticsearch:
        image: elasticsearch:5.6.5
        ports:
            - 9200:9200
            - 9300:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
