version: '2'
services:
    mqtt-elasticsearch-bridge:
        image: mqtt-elasticsearch-bridge
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - MEB_SLEEP=10 # gives time for services to boot before the application
        command: -e tcp://10.0.75.1:9300 -m tcp://10.0.75.1:1883
#        volumes:
#            -  ~/mebtemplates/template.json:/etc/meb/template.json
#    mosquitto:
#        extends:
#            file: mosquitto.yml
#            service: mosquitto
#    elasticsearch:
#        extends:
#            file: elasticsearch.yml
#            service: elasticsearch
